server:
    port:8081

spring:
    config:
        import:
            - optional:config/database.yml
springdoc:
  version: v1.0.0
  swagger-ui:
    disable-swagger-default-url: true
    path: /docs
  show-actuator: true